name: flutter_multiple_webview_plugin_example
description: Demonstrates how to use the flutter_multiple_webview_plugin plugin.
version: 1.0.10+1
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_multiple_webview_plugin:
    path: ../

flutter:
  uses-material-design: true
