name: flutter_multiple_webview_plugin
description: Plugin that allow Flutter to communicate with a multiple native Webviews.
authors:
- Peter Rozkošný <peter.rozkosny@powerplay.studio>
- Matej Snovák <matej.snovak@powerplay.studio>
version: 1.0.10
environment:
  sdk: '>=2.10.0 <3.0.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter_multiple_webview_plugin
        pluginClass: FlutterMultipleWebviewPlugin
      ios:
        pluginClass: FlutterMultipleWebviewPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter